version: '2'

services:

    opendlv-vehicle-view-amd64:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.39
        restart: on-failure
        volumes:
        - ./recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        #environment:
        #  join live session CID 48, replay on default CID 253
        #- OD4SESSION_CID=48
        ports:
        - "8081:8081"

    message-receiver:
        # this image need to build locally, the source file is in the receiver-replay folder
        image: receiver:v0.0.1
